version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: ./api-gateway/.env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    env_file: ./identity-service/.env
    environment:
      - JWT_SECRET=123@@@123@@@456@@456@@
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"
